### ISSUE TITLE
So this only works if I clone the repo via git?

### ISSUE THREAD

**Issue by smooJitter** [transistorsoft/rn-background-geolocation-demo#25]
So this only works if I clone the repo via git?

**Comment by christocracy** [comment]
This is a sample application implementing the background-geolocation plugin.

Yes, you must first clone the repo to install the app in sim or your device.

Or you can install the demo onto your Android device from [play store](https://play.google.com/store/apps/details?id=com.transistorsoft.rnbackgroundgeolocationsample)

**Comment by aseemk** [comment]
@christocracy: I notice this repo doesn't have a link to the Play Store, but both the background-geolocation repos (and the link has changed from your link above):

https://play.google.com/store/apps/details?id=com.transistorsoft.backgroundgeolocation.react

It looks like this version on the Play Store hasn't been updated since December. Is this easy for you to update?

That'd be convenient if so: I'd like to ask an Android-using coworker to install this app so we can compare its results to ours, and getting it from the Play Store would be less friction for that.

Thanks!
