### ISSUE TITLE
build.gradle missing the custom mavel url for react-native-background-fetch

### ISSUE THREAD

**Issue by kerembalcan** [transistorsoft/rn-background-geolocation-demo#93]
As mentioned in the documentations, a custom maven url should be defined for react-native-background-fetch. Currently android doesn't build and throws this error:

`   > Could not find any matches for com.transistorsoft:tsbackgroundfetch:+ as no versions of com.transistorsoft:tsbackgroundfetch are available.`

I add the documentation reference here:
https://github.com/transistorsoft/react-native-background-fetch/blob/master/docs/INSTALL-AUTO-ANDROID.md#open_file_folder-androidbuildgradle

**Comment by christocracy** [comment]
The demo in current `master` uses [`background-geolocation@3.7.0`](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/package.json#L23), [`background-fetch`](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/package.json#L22) and its gradle-tools at [`3.5.2`](https://github.com/transistorsoft/rn-background-geolocation-demo/blob/master/android/build.gradle#L23).

It doesn't require the `maven url`, unless you've explicitly installed versions beyond those above.

My local version has all these upgraded to latest, in addition to the `maven url`, due to be pushed in a few days.
